name: project_hcrl
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  url_launcher: ^6.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/pic/